from typing import Any, Protocol, TypeVar, runtime_checkable

import torch
import torch.nn as nn

T = TypeVar("T")


@runtime_checkable
class ToDictProtocol(Protocol):
    """Protocol for objects that have a to_dict method (like BatchEncoding)."""

    def to_dict(self) -> dict[str, Any]: ...


@runtime_checkable
class ModelWithTags(Protocol):
    """Protocol for models that support add_model_tags (TRL integration)."""

    def add_model_tags(self, tags: list[str]) -> None: ...


@runtime_checkable
class HFModelProtocol(Protocol):
    """
    Structural protocol for Hugging Face-like models.
    Defines common methods expected from a transformer backbone.
    """

    def generate(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_pretrained(self, save_directory: str, **kwargs: Any) -> None: ...
    def gradient_checkpointing_enable(self, **kwargs: Any) -> None: ...
    def gradient_checkpointing_disable(self, **kwargs: Any) -> None: ...

    @property
    def training(self) -> bool: ...

    @property
    def dtype(self) -> torch.dtype: ...

    @property
    def device(self) -> torch.device: ...

    @property
    def config(self) -> Any: ...

    def tie_weights(self) -> None: ...

    def to(self, *args: Any, **kwargs: Any) -> nn.Module: ...
    def parameters(self, recurse: bool = True) -> Any: ...
    def named_parameters(self, prefix: str = "", recurse: bool = True) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_forward_pre_hook(self, hook: Any, **kwargs: Any) -> Any: ...
